application: trojan-tech-tickets
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  login: required
  script: _go_app
- url: /status
  login: admin
  script: _go_app
- url: /workers
  login: admin
  script: _go_app
